import { Employee, AttendanceRecord, LeaveRequest, PayrollRecord, NotificationItem } from '../types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    employeeId: 'EMP-0001',
    name: 'Sarah Jenkins',
    email: 'admin@dayflow.com',
    role: 'ADMIN_HR',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
    phone: '+1 (555) 123-4567',
    address: '742 Evergreen Terrace, San Francisco, CA 94107',
    designation: 'VP of People & Culture',
    department: 'Human Resources',
    joiningDate: '2021-03-15',
    employmentType: 'Full-Time',
    managerName: 'Board of Directors',
    isEmailVerified: true,
    bio: 'People operations strategist with 10+ years scaling high-growth tech teams, talent acquisition, and company culture.',
    about: 'Strategic HR leader with a passion for designing scalable compensation frameworks, talent programs, and inclusive workplace cultures.',
    whatILoveAboutJob: 'Empowering cross-functional teams, solving workforce growth challenges, and seeing people thrive in their careers.',
    interestsAndHobbies: 'Trail running, sourdough baking, classical violin, and reading leadership biographies.',
    skills: ['People Operations', 'Compensation & Benefits', 'Strategic Hiring', 'Conflict Resolution', 'Executive Coaching'],
    certifications: [
      { id: 'c1', name: 'SHRM Senior Certified Professional (SHRM-SCP)', issuer: 'SHRM', date: '2022-04-10' },
      { id: 'c2', name: 'Global Talent Strategy Certification', issuer: 'HRCI', date: '2023-09-15' }
    ],
    privateInfo: {
      dateOfBirth: '1988-11-24',
      residingAddress: '742 Evergreen Terrace, San Francisco, CA 94107',
      nationality: 'American',
      personalEmail: 'sarah.jenkins.personal@gmail.com',
      gender: 'Female',
      maritalStatus: 'Married',
      dateOfJoining: '2021-03-15',
      bankName: 'Silicon Valley Bank',
      accountNumber: '987654321001',
      ifscCode: 'SVNB0001001',
      panNumber: 'SRHJK1001A',
      uanNumber: '100987654001'
    },
    salaryStructure: {
      monthlyWage: 75000,
      yearlyWage: 900000,
      workingDaysPerWeek: 5,
      workingHoursPerDay: 8,
      breakTimeHours: 1,
      baseSalary: 37500,
      hra: 18750,
      standardAllowance: 6250,
      performanceBonus: 3125,
      leaveTravelAllowance: 3125,
      fixedAllowance: 6250,
      conveyance: 800,
      specialAllowance: 1200,
      providentFund: 4500,
      employerPF: 4500,
      professionalTax: 200,
      bonus: 3125,
      currency: 'INR'
    },
    documents: [
      { id: 'doc-1', name: 'Executive_Employment_Agreement.pdf', type: 'Contract', uploadDate: '2021-03-15', size: '2.4 MB' },
      { id: 'doc-2', name: 'Identity_Verification_Passport.pdf', type: 'ID Proof', uploadDate: '2021-03-16', size: '1.8 MB' },
      { id: 'doc-3', name: 'HR_Compliance_Certification.pdf', type: 'Certificate', uploadDate: '2023-01-10', size: '950 KB' }
    ],
    leaveBalance: {
      paid: { total: 24, used: 4, remaining: 20 },
      sick: { total: 10, used: 1, remaining: 9 },
      casual: { total: 6, used: 2, remaining: 4 },
      unpaid: { used: 0 }
    },
    emergencyContact: {
      name: 'Robert Jenkins',
      relationship: 'Spouse',
      phone: '+1 (555) 987-6543'
    }
  },
  {
    id: 'emp-002',
    employeeId: 'EMP-1002',
    name: 'Alex Morgan',
    email: 'employee@dayflow.com',
    role: 'EMPLOYEE',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
    phone: '+1 (555) 234-5678',
    address: '120 Market St, Apt 4B, San Francisco, CA 94102',
    designation: 'Senior Full Stack Engineer',
    department: 'Engineering',
    joiningDate: '2022-08-01',
    employmentType: 'Full-Time',
    managerName: 'Sarah Jenkins',
    isEmailVerified: true,
    bio: 'Passionate full-stack developer specializing in modern React, TypeScript, GraphQL, and microservices architecture.',
    about: 'Full-stack builder focused on delightful UI architecture, high performance distributed APIs, and automated CI/CD deployments.',
    whatILoveAboutJob: 'Building robust software products that solve real-world problems for thousands of daily enterprise users.',
    interestsAndHobbies: 'Competitive coding, hiking national parks, playing synthesizers, and mechanical keyboards.',
    skills: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'PostgreSQL', 'Tailwind CSS', 'Docker'],
    certifications: [
      { id: 'c3', name: 'AWS Certified Solutions Architect', issuer: 'Amazon Web Services', date: '2023-06-20' },
      { id: 'c4', name: 'Meta Front-End Developer Specialization', issuer: 'Meta', date: '2022-11-12' }
    ],
    privateInfo: {
      dateOfBirth: '1994-05-18',
      residingAddress: '120 Market St, Apt 4B, San Francisco, CA 94102',
      nationality: 'American',
      personalEmail: 'alex.morgan.dev@gmail.com',
      gender: 'Male',
      maritalStatus: 'Single',
      dateOfJoining: '2022-08-01',
      bankName: 'Chase Bank',
      accountNumber: '987654321002',
      ifscCode: 'CHAS0001002',
      panNumber: 'ALXMG1002B',
      uanNumber: '100987654002'
    },
    salaryStructure: {
      monthlyWage: 50000,
      yearlyWage: 600000,
      workingDaysPerWeek: 5,
      workingHoursPerDay: 8,
      breakTimeHours: 1,
      baseSalary: 25000,
      hra: 12500,
      standardAllowance: 4167,
      performanceBonus: 2082.5,
      leaveTravelAllowance: 2082.5,
      fixedAllowance: 4168,
      conveyance: 600,
      specialAllowance: 1100,
      providentFund: 3000,
      employerPF: 3000,
      professionalTax: 200,
      bonus: 2082.5,
      currency: 'INR'
    },
    documents: [
      { id: 'doc-4', name: 'Software_Engineer_Contract_Signed.pdf', type: 'Contract', uploadDate: '2022-08-01', size: '3.1 MB' },
      { id: 'doc-5', name: 'Drivers_License_Verification.pdf', type: 'ID Proof', uploadDate: '2022-08-02', size: '1.2 MB' },
      { id: 'doc-6', name: 'W4_Tax_Withholding_2026.pdf', type: 'Tax Form', uploadDate: '2026-01-05', size: '420 KB' }
    ],
    leaveBalance: {
      paid: { total: 18, used: 5, remaining: 13 },
      sick: { total: 8, used: 2, remaining: 6 },
      casual: { total: 6, used: 1, remaining: 5 },
      unpaid: { used: 0 }
    },
    emergencyContact: {
      name: 'Claire Morgan',
      relationship: 'Sister',
      phone: '+1 (555) 876-5432'
    }
  },
  {
    id: 'emp-003',
    employeeId: 'EMP-1003',
    name: 'Elena Rostova',
    email: 'elena@dayflow.com',
    role: 'EMPLOYEE',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=250&auto=format&fit=crop&q=80',
    phone: '+1 (555) 345-6789',
    address: '450 Mission St, San Francisco, CA 94105',
    designation: 'Lead Product Designer',
    department: 'Design & UX',
    joiningDate: '2023-06-15',
    employmentType: 'Full-Time',
    managerName: 'Sarah Jenkins',
    isEmailVerified: true,
    bio: 'Design system fanatic crafting human-centric digital experiences with pixel perfection.',
    about: 'Senior Product Designer transforming complex workflows into clean, accessible, and intuitive visual interfaces.',
    whatILoveAboutJob: 'Designing frictionless user flows, micro-interactions, and design systems that designers and developers love using.',
    interestsAndHobbies: 'Typography, oil painting, architecture, and interior design.',
    skills: ['Figma', 'Design Systems', 'UX Research', 'Prototyping', 'Accessibility (WCAG)'],
    certifications: [
      { id: 'c5', name: 'Nielsen Norman UX Master Certified', issuer: 'NN/g', date: '2023-02-14' }
    ],
    privateInfo: {
      dateOfBirth: '1992-09-10',
      residingAddress: '450 Mission St, San Francisco, CA 94105',
      nationality: 'American',
      personalEmail: 'elena.rostova.design@gmail.com',
      gender: 'Female',
      maritalStatus: 'Single',
      dateOfJoining: '2023-06-15',
      bankName: 'Wells Fargo',
      accountNumber: '987654321003',
      ifscCode: 'WFBI0001003',
      panNumber: 'ELNRST1003C',
      uanNumber: '100987654003'
    },
    salaryStructure: {
      monthlyWage: 48000,
      yearlyWage: 576000,
      workingDaysPerWeek: 5,
      workingHoursPerDay: 8,
      breakTimeHours: 1,
      baseSalary: 24000,
      hra: 12000,
      standardAllowance: 4000,
      performanceBonus: 2000,
      leaveTravelAllowance: 2000,
      fixedAllowance: 4000,
      conveyance: 500,
      specialAllowance: 900,
      providentFund: 2880,
      employerPF: 2880,
      professionalTax: 200,
      bonus: 2000,
      currency: 'INR'
    },
    documents: [
      { id: 'doc-7', name: 'Employment_Contract_Design.pdf', type: 'Contract', uploadDate: '2023-06-15', size: '2.1 MB' }
    ],
    leaveBalance: {
      paid: { total: 18, used: 3, remaining: 15 },
      sick: { total: 8, used: 0, remaining: 8 },
      casual: { total: 6, used: 2, remaining: 4 },
      unpaid: { used: 0 }
    }
  },
  {
    id: 'emp-004',
    employeeId: 'EMP-1004',
    name: 'David Kim',
    email: 'david@dayflow.com',
    role: 'EMPLOYEE',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=250&auto=format&fit=crop&q=80',
    phone: '+1 (555) 456-7890',
    address: '890 Folsom St, San Francisco, CA 94107',
    designation: 'DevOps & Cloud Architect',
    department: 'Infrastructure',
    joiningDate: '2022-11-10',
    employmentType: 'Full-Time',
    managerName: 'Alex Morgan',
    isEmailVerified: true,
    bio: 'Kubernetes maestro, Terraform enthusiast, maintaining 99.99% uptime for global systems.',
    about: 'Cloud infrastructure architect focused on Kubernetes orchestration, immutable deployments, and zero-trust security.',
    whatILoveAboutJob: 'Ensuring ultra-resilient distributed systems with zero downtime and sub-second latency.',
    interestsAndHobbies: 'Home automation, rock climbing, robotics, and espresso brewing.',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'GCP', 'Linux Kernel', 'Prometheus & Grafana'],
    certifications: [
      { id: 'c6', name: 'Certified Kubernetes Administrator (CKA)', issuer: 'Linux Foundation', date: '2023-01-20' }
    ],
    privateInfo: {
      dateOfBirth: '1991-03-30',
      residingAddress: '890 Folsom St, San Francisco, CA 94107',
      nationality: 'American',
      personalEmail: 'david.kim.infra@gmail.com',
      gender: 'Male',
      maritalStatus: 'Married',
      dateOfJoining: '2022-11-10',
      bankName: 'Bank of America',
      accountNumber: '987654321004',
      ifscCode: 'BOFA0001004',
      panNumber: 'DVDKM1004D',
      uanNumber: '100987654004'
    },
    salaryStructure: {
      monthlyWage: 55000,
      yearlyWage: 660000,
      workingDaysPerWeek: 5,
      workingHoursPerDay: 8,
      breakTimeHours: 1,
      baseSalary: 27500,
      hra: 13750,
      standardAllowance: 4583,
      performanceBonus: 2291.5,
      leaveTravelAllowance: 2291.5,
      fixedAllowance: 4584,
      conveyance: 700,
      specialAllowance: 1300,
      providentFund: 3300,
      employerPF: 3300,
      professionalTax: 200,
      bonus: 2291.5,
      currency: 'INR'
    },
    documents: [
      { id: 'doc-8', name: 'DevOps_Architect_Contract.pdf', type: 'Contract', uploadDate: '2022-11-10', size: '2.8 MB' },
      { id: 'doc-9', name: 'AWS_Solutions_Architect_Pro.pdf', type: 'Certificate', uploadDate: '2024-02-18', size: '1.1 MB' }
    ],
    leaveBalance: {
      paid: { total: 18, used: 6, remaining: 12 },
      sick: { total: 8, used: 3, remaining: 5 },
      casual: { total: 6, used: 0, remaining: 6 },
      unpaid: { used: 0 }
    }
  },
  {
    id: 'emp-005',
    employeeId: 'EMP-1005',
    name: 'Priya Sharma',
    email: 'priya@dayflow.com',
    role: 'EMPLOYEE',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
    phone: '+1 (555) 567-8901',
    address: '320 Hayes St, San Francisco, CA 94102',
    designation: 'Product Marketing Lead',
    department: 'Growth & Marketing',
    joiningDate: '2023-01-20',
    employmentType: 'Full-Time',
    managerName: 'Sarah Jenkins',
    isEmailVerified: true,
    bio: 'Storyteller, growth catalyst, connecting customer problems to delightful product capabilities.',
    about: 'Go-to-market leader bridging engineering excellence with clear customer narratives and data-driven growth funnels.',
    whatILoveAboutJob: 'Translating complex product innovations into compelling stories that resonate with customers globally.',
    interestsAndHobbies: 'Podcasting, urban sketching, pottery, and culinary arts.',
    skills: ['Product Marketing', 'Growth Analytics', 'Customer Lifecycle', 'Content Strategy', 'Brand Positioning'],
    certifications: [
      { id: 'c7', name: 'Product Marketing Certified (PMMC)', issuer: 'PMA', date: '2023-05-19' }
    ],
    privateInfo: {
      dateOfBirth: '1993-12-05',
      residingAddress: '320 Hayes St, San Francisco, CA 94102',
      nationality: 'American',
      personalEmail: 'priya.sharma.growth@gmail.com',
      gender: 'Female',
      maritalStatus: 'Single',
      dateOfJoining: '2023-01-20',
      bankName: 'Citibank',
      accountNumber: '987654321005',
      ifscCode: 'CITI0001005',
      panNumber: 'PRYSH1005E',
      uanNumber: '100987654005'
    },
    salaryStructure: {
      monthlyWage: 46000,
      yearlyWage: 552000,
      workingDaysPerWeek: 5,
      workingHoursPerDay: 8,
      breakTimeHours: 1,
      baseSalary: 23000,
      hra: 11500,
      standardAllowance: 3833,
      performanceBonus: 1916.5,
      leaveTravelAllowance: 1916.5,
      fixedAllowance: 3834,
      conveyance: 500,
      specialAllowance: 800,
      providentFund: 2760,
      employerPF: 2760,
      professionalTax: 200,
      bonus: 1916.5,
      currency: 'INR'
    },
    documents: [
      { id: 'doc-10', name: 'Marketing_Lead_Agreement.pdf', type: 'Contract', uploadDate: '2023-01-20', size: '1.9 MB' }
    ],
    leaveBalance: {
      paid: { total: 18, used: 2, remaining: 16 },
      sick: { total: 8, used: 0, remaining: 8 },
      casual: { total: 6, used: 1, remaining: 5 },
      unpaid: { used: 0 }
    }
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Today's records (Aug 22, 2026)
  {
    id: 'att-101',
    employeeId: 'EMP-0001',
    employeeName: 'Sarah Jenkins',
    date: '2026-08-22',
    checkIn: '08:45 AM',
    checkOut: null,
    workingHours: 9.0,
    extraHours: 1.0,
    status: 'PRESENT'
  },
  {
    id: 'att-102',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    date: '2026-08-22',
    checkIn: '09:05 AM',
    checkOut: null,
    workingHours: 8.5,
    extraHours: 0.5,
    status: 'PRESENT'
  },
  {
    id: 'att-103',
    employeeId: 'EMP-1003',
    employeeName: 'Elena Rostova',
    date: '2026-08-22',
    checkIn: '09:30 AM',
    checkOut: null,
    workingHours: 8.0,
    extraHours: 0,
    status: 'PRESENT'
  },
  {
    id: 'att-104',
    employeeId: 'EMP-1004',
    employeeName: 'David Kim',
    date: '2026-08-22',
    checkIn: null,
    checkOut: null,
    workingHours: 0,
    extraHours: 0,
    status: 'LEAVE',
    notes: 'Approved Sick Leave'
  },
  {
    id: 'att-105',
    employeeId: 'EMP-1005',
    employeeName: 'Priya Sharma',
    date: '2026-08-22',
    checkIn: '09:12 AM',
    checkOut: null,
    workingHours: 9.5,
    extraHours: 1.5,
    status: 'PRESENT'
  },

  // Past Days History
  {
    id: 'att-106',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    date: '2026-08-21',
    checkIn: '09:00 AM',
    checkOut: '06:30 PM',
    workingHours: 9.5,
    extraHours: 1.5,
    status: 'PRESENT'
  },
  {
    id: 'att-107',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    date: '2026-08-20',
    checkIn: '09:15 AM',
    checkOut: '06:15 PM',
    workingHours: 9.0,
    extraHours: 1.0,
    status: 'PRESENT'
  },
  {
    id: 'att-108',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    date: '2026-08-19',
    checkIn: '08:55 AM',
    checkOut: '05:55 PM',
    workingHours: 9.0,
    extraHours: 1.0,
    status: 'PRESENT'
  },
  {
    id: 'att-109',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    date: '2026-08-18',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workingHours: 9.0,
    extraHours: 1.0,
    status: 'PRESENT'
  },
  {
    id: 'att-110',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    date: '2026-08-15',
    checkIn: null,
    checkOut: null,
    workingHours: 0,
    extraHours: 0,
    status: 'LEAVE',
    notes: 'Paid Vacation Day'
  },
  {
    id: 'att-111',
    employeeId: 'EMP-1003',
    employeeName: 'Elena Rostova',
    date: '2026-08-21',
    checkIn: '09:30 AM',
    checkOut: '06:30 PM',
    workingHours: 9.0,
    extraHours: 1.0,
    status: 'PRESENT'
  },
  {
    id: 'att-112',
    employeeId: 'EMP-1003',
    employeeName: 'Elena Rostova',
    date: '2026-08-20',
    checkIn: '10:00 AM',
    checkOut: '07:00 PM',
    workingHours: 9.0,
    extraHours: 1.0,
    status: 'PRESENT'
  },
  {
    id: 'att-113',
    employeeId: 'EMP-0001',
    employeeName: 'Sarah Jenkins',
    date: '2026-08-21',
    checkIn: '08:30 AM',
    checkOut: '05:45 PM',
    workingHours: 9.25,
    extraHours: 1.25,
    status: 'PRESENT'
  },
  {
    id: 'att-114',
    employeeId: 'EMP-1004',
    employeeName: 'David Kim',
    date: '2026-08-21',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workingHours: 9.0,
    extraHours: 1.0,
    status: 'PRESENT'
  }
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'leave-001',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
    department: 'Engineering',
    leaveType: 'PAID',
    startDate: '2026-09-01',
    endDate: '2026-09-04',
    totalDays: 4,
    reason: 'Annual family vacation trip to Hawaii.',
    status: 'PENDING',
    appliedOn: '2026-08-18'
  },
  {
    id: 'leave-002',
    employeeId: 'EMP-1004',
    employeeName: 'David Kim',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=250&auto=format&fit=crop&q=80',
    department: 'Infrastructure',
    leaveType: 'SICK',
    startDate: '2026-08-22',
    endDate: '2026-08-23',
    totalDays: 2,
    reason: 'Severe seasonal flu symptoms and medical doctor appointment.',
    status: 'APPROVED',
    appliedOn: '2026-08-21',
    adminComment: 'Get well soon David! Take full rest.',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: '2026-08-21 16:30'
  },
  {
    id: 'leave-003',
    employeeId: 'EMP-1003',
    employeeName: 'Elena Rostova',
    employeeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=250&auto=format&fit=crop&q=80',
    department: 'Design & UX',
    leaveType: 'CASUAL',
    startDate: '2026-08-28',
    endDate: '2026-08-28',
    totalDays: 1,
    reason: 'Personal errand and house relocation setup.',
    status: 'PENDING',
    appliedOn: '2026-08-20'
  },
  {
    id: 'leave-004',
    employeeId: 'EMP-1005',
    employeeName: 'Priya Sharma',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
    department: 'Growth & Marketing',
    leaveType: 'PAID',
    startDate: '2026-07-14',
    endDate: '2026-07-16',
    totalDays: 3,
    reason: 'Annual family reunion.',
    status: 'APPROVED',
    appliedOn: '2026-07-05',
    adminComment: 'Approved, have a great time!',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: '2026-07-06 10:15'
  }
];

export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'pay-001',
    employeeId: 'EMP-0001',
    employeeName: 'Sarah Jenkins',
    month: 'July',
    year: 2026,
    totalWorkingDays: 22,
    presentDays: 21,
    paidLeaveDays: 1,
    unpaidDays: 0,
    payableDays: 22,
    basic: 37500,
    hra: 18750,
    allowances: 12500,
    bonus: 3125,
    grossSalary: 75000,
    pf: 4500,
    tax: 200,
    lopDeduction: 0,
    totalDeductions: 4700,
    netPay: 70300,
    status: 'PAID',
    paymentDate: '2026-07-31'
  },
  {
    id: 'pay-002',
    employeeId: 'EMP-1002',
    employeeName: 'Alex Morgan',
    month: 'July',
    year: 2026,
    totalWorkingDays: 22,
    presentDays: 20,
    paidLeaveDays: 2,
    unpaidDays: 0,
    payableDays: 22,
    basic: 25000,
    hra: 12500,
    allowances: 8335,
    bonus: 2082.5,
    grossSalary: 50000,
    pf: 3000,
    tax: 200,
    lopDeduction: 0,
    totalDeductions: 3200,
    netPay: 46800,
    status: 'PAID',
    paymentDate: '2026-07-31'
  },
  {
    id: 'pay-003',
    employeeId: 'EMP-1003',
    employeeName: 'Elena Rostova',
    month: 'July',
    year: 2026,
    totalWorkingDays: 22,
    presentDays: 22,
    paidLeaveDays: 0,
    unpaidDays: 0,
    payableDays: 22,
    basic: 24000,
    hra: 12000,
    allowances: 8000,
    bonus: 2000,
    grossSalary: 48000,
    pf: 2880,
    tax: 200,
    lopDeduction: 0,
    totalDeductions: 3080,
    netPay: 44920,
    status: 'PAID',
    paymentDate: '2026-07-31'
  },
  {
    id: 'pay-004',
    employeeId: 'EMP-1004',
    employeeName: 'David Kim',
    month: 'July',
    year: 2026,
    totalWorkingDays: 22,
    presentDays: 21,
    paidLeaveDays: 1,
    unpaidDays: 0,
    payableDays: 22,
    basic: 27500,
    hra: 13750,
    allowances: 9167,
    bonus: 2291.5,
    grossSalary: 55000,
    pf: 3300,
    tax: 200,
    lopDeduction: 0,
    totalDeductions: 3500,
    netPay: 51500,
    status: 'PAID',
    paymentDate: '2026-07-31'
  },
  {
    id: 'pay-005',
    employeeId: 'EMP-1005',
    employeeName: 'Priya Sharma',
    month: 'July',
    year: 2026,
    totalWorkingDays: 22,
    presentDays: 19,
    paidLeaveDays: 3,
    unpaidDays: 0,
    payableDays: 22,
    basic: 23000,
    hra: 11500,
    allowances: 7667,
    bonus: 1916.5,
    grossSalary: 46000,
    pf: 2760,
    tax: 200,
    lopDeduction: 0,
    totalDeductions: 2960,
    netPay: 43040,
    status: 'PAID',
    paymentDate: '2026-07-31'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-001',
    userId: 'ALL',
    title: 'New Leave Request Submitted',
    message: 'Alex Morgan submitted a request for 4 days of Paid Leave.',
    type: 'leave',
    timestamp: '10 mins ago',
    read: false,
    link: '/leaves'
  },
  {
    id: 'notif-002',
    userId: 'EMP-1004',
    title: 'Sick Leave Approved',
    message: 'Your 2-day Sick Leave request for Aug 22-23 was approved by Sarah Jenkins.',
    type: 'success',
    timestamp: '2 hours ago',
    read: false,
    link: '/leaves'
  },
  {
    id: 'notif-003',
    userId: 'ALL',
    title: 'Monthly Salary Statements Ready',
    message: 'July 2026 payroll compensation has been successfully disbursed.',
    type: 'payroll',
    timestamp: '1 day ago',
    read: true,
    link: '/payroll'
  },
  {
    id: 'notif-004',
    userId: 'EMP-1002',
    title: 'Shift Punch-In Recorded',
    message: 'Shift started today at 09:05 AM. Have a great day!',
    type: 'attendance',
    timestamp: 'Today at 09:05 AM',
    read: true,
    link: '/attendance'
  }
];
